# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import scontrini.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160422_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='selected_shop',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='category',
            field=models.CharField(blank=True, choices=[('Alimentari', 'Alimentari'), ('Benzina', 'Benzina')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(upload_to=scontrini.main.models.user_directory_path),
        ),
    ]
