# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160422_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='shop',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
