# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_receipt_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='has_position',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='long',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='category',
            field=models.CharField(blank=True, choices=[('Affitto', 'Affitto'), ('Alberghi e ristoranti', 'Alberghi e ristoranti'), ('Altro', 'Altro'), ('Automobile', 'Automobile'), ('Bollette', 'Bollette'), ('Intrattenimento', 'Intrattenimento'), ('Spesa', 'Spesa'), ('Vestiti', 'Vestiti')], max_length=200, null=True),
        ),
    ]
