# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 19:38
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160422_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='price_list',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
